SVG_COLOR = "#f0f0f0"
ANNOTATION_TOOL_SIZES = [1, 2, 4, 6, 8, 12, 16, 20, 30, 40, 50, 75, 100, 125, 150, 200, 250, 300]
ANNOTATION_TEXT_SIZES = [2, 4, 6, 8, 9, 10, 11, 12, 14, 18, 24, 30, 36, 48, 60, 72, 96]

INTERACTIVE_MODE = "interactive_mode"
INTERACTIVE_MODE_RECTANGLE = "rectangle"
INTERACTIVE_MODE_ELLIPSE = "ellipse"
INTERACTIVE_MODE_LASSO = "lasso"
INTERACTIVE_MODE_PEN = "pen"
INTERACTIVE_MODE_LINE = "line"
INTERACTIVE_MODE_MULTI_LINE = "multi_line"
INTERACTIVE_MODE_AIRBRUSH = "airbrush"
INTERACTIVE_MODE_TEXT = "text"
INTERACTIVE_MODE_HARD_ERASER = "hard_eraser"
INTERACTIVE_MODE_SOFT_ERASER = "soft_eraser"
INTERACTIVE_MODE_MOVE = "move"

TIMELINE_SELECTED_KEYS = "selected_timeline_keys"
MIME_TYPE_ANNOTATION_LIST = 'itview/annotations'
