DEFAULT_OFFSET = (0, 0, 0)
DEFAULT_SLOPE = (1, 1, 1)
DEFAULT_POWER = (1, 1, 1)
DEFAULT_SAT = 1

DEFAULT_FSTOP = (1, 1, 1)
DEFAULT_GAMMA = (1, 1, 1)
DEFAULT_BLACKPOINT = (0, 0, 0)
DEFAULT_WHITEPOINT = (1, 1, 1)
DEFAULT_LIFT = (0, 0, 0)

DEFAULT_FALLOFF = 0

INTERACTIVE_MODE = "interactive_mode"
INTERACTIVE_MODE_RECTANGLE = "rectangle"
INTERACTIVE_MODE_ELLIPSE = "ellipse"
INTERACTIVE_MODE_LASSO = "lasso"
